---
- name: Shutdown VM and Remove it from Proxmox
  hosts: all
  tasks:

    - name: Shutdown VM
      community.general.proxmox_kvm:
        node: "{{ proxmox_node }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        name: "{{ vm_name }}"
        state: stopped

    - name: wait 20 seconds
      ansible.builtin.pause:
        seconds: 20

    - name: Remove VM
      community.general.proxmox_kvm:
        node: "{{ proxmox_node }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        name: "{{ vm_name }}"
        state: absent