---
- name: Restart VM
  hosts: all
  tasks:

    - name: Restart VM
      community.general.proxmox_kvm:
        node: "{{ proxmox_node }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        name: "{{ vm_name }}"
        state: restarted