---
- hosts: all
  become: true
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Clean up apt cache
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes